### ISSUE TITLE
Camera shown as Offline on Controller

### ISSUE THREAD

**Issue by bensteUEM** [josephdadams/udp-to-serial#1]
Hi Jospeph,
i've tried your script and our Marshall VS-PTC-IP Controller correctly connects to the node at first.
However after sending some first messages our controller believes the camera to be offline an no longer sends out commands:

```
Opening Serial Port: /dev/ttyUSB0
Baud Rate: 9600
Socket listening at: 0.0.0.0:52381
Received 9 bytes from 192.168.2.141:58893

Received 16 bytes from 192.168.2.141:58893

Received 9 bytes from 192.168.2.141:58893

Received 9 bytes from 192.168.2.141:33997

Received 16 bytes from 192.168.2.141:33997

Received 9 bytes from 192.168.2.141:33997

```

Is this related to your module or would RS232 communication also provide some sort of feedback - i seem to have some issues connecting to my camera too ...

**Comment by bensteUEM** [comment]
I did manage to use the Sony Visca Module in Companion and run it through you module successfully after rewiring my rs232 to rj45 and setting visca1 address on the camera (as opposed to its default 0)

Guess this means that visca-ip used by the controller and visca over rs232 are not identical?

Do you think it's worth tweaking your script to display the actual message received instead of showing bytes only?

**Comment by josephdadams** [comment]
I would suggest seeing what the camera normally sends back over serial and sending that back with this script on every message. It’s probably an ACK of some kind.
